
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.237.138:3306/mall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 112.126.80.104
    port: 5672
    virtual-host: /
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  #设置主键自增
server:
  port: 9000
